// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.Persistence.DBContext;

namespace Tienda.Persistence.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20200111002500_Primero")]
    partial class Primero
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tienda.Persistence.Entities.Carrito", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSale")
                        .HasColumnType("int");

                    b.Property<int?>("SaleIdSale")
                        .HasColumnType("int");

                    b.HasKey("IdCar");

                    b.HasIndex("SaleIdSale");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Categoria", b =>
                {
                    b.Property<string>("NomCategoria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomCategoria");

                    b.ToTable("Categroria");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Prod_Car", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarritoIdCar")
                        .HasColumnType("int");

                    b.Property<int>("IdCar")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CarritoIdCar");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("ProdCar");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaNomCategoria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CategoriaNomCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSale");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Carrito", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Sale", "Sale")
                        .WithMany("Carrito")
                        .HasForeignKey("SaleIdSale");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Prod_Car", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Carrito", "Carrito")
                        .WithMany("ProdCar")
                        .HasForeignKey("CarritoIdCar");

                    b.HasOne("Tienda.Persistence.Entities.Producto", "Producto")
                        .WithMany("ProdCar")
                        .HasForeignKey("ProductoIdProducto");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Producto", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("CategoriaNomCategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
