// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.Persistence.DBContext;

namespace Tienda.Persistence.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20200121191134_CantidadenProdCar")]
    partial class CantidadenProdCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tienda.Persistence.Entities.Carrito", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCar");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Categoria", b =>
                {
                    b.Property<string>("NomCategoria")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomCategoria");

                    b.ToTable("Categroria");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Prod_Car", b =>
                {
                    b.Property<int>("IdProdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("CarritoIdCar")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProdCar");

                    b.HasIndex("CarritoIdCar");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("ProdCar");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CategoriaNomCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CategoriaNomCategoria");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Sale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("carritoIdCar")
                        .HasColumnType("int");

                    b.HasKey("IdSale");

                    b.HasIndex("carritoIdCar");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Prod_Car", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Carrito", "Carrito")
                        .WithMany("ProdCar")
                        .HasForeignKey("CarritoIdCar");

                    b.HasOne("Tienda.Persistence.Entities.Producto", "Producto")
                        .WithMany("ProdCar")
                        .HasForeignKey("ProductoIdProducto");
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Producto", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("CategoriaNomCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tienda.Persistence.Entities.Sale", b =>
                {
                    b.HasOne("Tienda.Persistence.Entities.Carrito", "carrito")
                        .WithMany("sale")
                        .HasForeignKey("carritoIdCar");
                });
#pragma warning restore 612, 618
        }
    }
}
